version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ./app: /var/www/html
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - ./app/web/spa:/var/www/html/web/spa:ro
      - ./app:/var/www/html/app:ro
    ports:
      - '8000:80'
